### ISSUE TITLE
Good guys

### ISSUE THREAD

**Issue by jiandeheng** [BigDeep/com.graduate.trip.reimbursement#1]
7 an

**Comment by BigDeep** [comment]
噗呲啊噗呲

**Comment by BigDeep** [comment]
Plz commit your issues imitating these under templates? ok?


### Brief description of bug
#### Self-Diagnosis
- [x] I have reviewed the documentation.
- [x] I have reviewed the Wiki.
- [x] I have tried to use the latest version.
- [x] I have searched the issues for an answer to my question. 
- [x] I have searched the web for an answer to my question.

#### Environment(for bug reports)
- [x] Operating System:
- [x] IDE version:
- [x] Plugin version:

#### My configuration/Related code

#### Steps to Reproduce the Issue

#### Current Result (Include screenshots where appropriate.)

#### Expected Result

**Comment by jiandeheng** [comment]
ok fine, you say something so something
